### ISSUE TITLE
Is there a reason you've used the plugins directory?

### ISSUE THREAD

**Issue by andybak** [hww/koch_fractals#2]
From https://docs.unity3d.com/Manual/SpecialFolders.html

> Plug-ins are native DLLs that are typically written in C/C++. They can access third-party code libraries, system calls and other Unity built-in functionality. Always place plug-ins in a folder called Plugins for them to be detected by Unity.
> 
> You can only have one Plugins folder and it must be placed in the root of the Project; directly within the Assets folder.

This doesn't seem to apply in your case.

**Comment by hww** [comment]
An additional benefit of plugins folder is that, due to order of plugin folder compilation,
compilation of plugins is separate from compilation of the game. Bugs or changes in one does not
require re-compilation of the other.

https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html

That is why i drop to plugins anything which is not my game project.
You can do it your own way, just copy this folder anywhere you want.
Other words: no any reason to keep it in plugins folder other then if you want it.
